### PR TITLE
PTW: check all reserved bits for non-leaf ptes

### PR DESCRIPTION
**Pull request by poemonsense**
Non-leaf PTEs should not have any of D, A, and U bits set, otherwise a page-fault exception is raised.

Previously rocket-chip is missing the condition for D, A, and U bits.

**Related issue**: 

**Type of change**: bug report

**Impact**: API modification

**Development Phase**: implementation

**Release Notes**

See https://github.com/chipsalliance/rocket-chip/issues/3402#issuecomment-1614229185 for more information on the bug.

### CODE REVIEW

**Comment by poemonsense** [comment]
@aswaterman Would you mind take a quick look at this as well? Rocket-chip is missing the conditions for non-leaf page-fault. It checks the conditions in table but fails to report it as a page-fault. Thanks.

**Review by aswaterman — COMMENTED** [review]
cc @ingallsj again, but this looks right to me.

I'd suggest the name `isReservedIfNonLeaf`.

**Comment by ingallsj** [comment]
Looking, and attempting to reproduce the bug and fix internally, too.  Standby.

**Comment by poemonsense** [comment]
Changed the name to `isReservedIfNonLeaf` as suggested.

**Review by ingallsj — CHANGES_REQUESTED** [review]
Because the definition of a non-leaf "table" PTE is that the R,W,X permission bits are zeroes "off", the L1TLB (ITLB/DTLB) then goes on to report a page fault, even though the PTW response did not explicitly include the `pf` bit set.

So we think that this change would add redundant logic to what the L1TLB (ITLB/DTLB) already performs, and we don't think there is a bug that this change fixes.

**Comment by poemonsense** [comment]
After double-checking the case, I found you are right and this bug depends on a wrong patch for #3407. Before I submit the final and correct PR for that, I had a bad patch trying to fix #3407. This bug is only feasible in that version. 

Sorry for the confusion and thanks for your work. I'll close this PR.

**Pull request closed without merging**
