### PR TITLE
Add HasBlackBoxResource to EICG_wrapper so that it ends up in the .f file

### PR DESCRIPTION
**Pull request by jwright6323**
**Related issue**: 

**Type of change**: other enhancement

**Impact**: no functional change

**Development Phase**: implementation

**Release Notes**
This adds HasBlackBoxResource to the EICG_wrapper blackbox so that it ends up in the .f file.

### CODE REVIEW

**Comment by aswaterman** [comment]
IIRC, the reason we didn’t do this is that it interferes with having different process-specific implementations of this module with the same module name but at different paths.

**Comment by jwright6323** [comment]
Ah, ok. Couldn't you override the `ClockGateImpl` config to the process-specific wrapper to accomplish the same thing? I guess that would be an "API change", though.

**Comment by aswaterman** [comment]
Yeah, that would work, but it would cause us a lot of trouble.  As it is, this way at least fails noisily: if you fail to provide an implementation, you'll get a linkage error, rather than a broken circuit.

**Comment by sequencer** [comment]
closed since #2969 merged.

**Pull request closed without merging**
