### PR TITLE
add dev branch and switch to chisel master

### PR DESCRIPTION
**Pull request by sequencer**
Since Chisel 3.6 is introducing more and more breaking changes(#3242, #3210, #3200, #3169, #2968), while Chisel 5(the next version of Chisel 3.6) will introduce more, and not back porting them. For the developers who wanna use new feature to develop RocketChip is a burden to wait for new release of Chisel release(almost half to one year for a major version). And I'm also tired of maintaining a bunch of patches which will be eventually merged but blocked by Chisel release.  I'm proposing to switch rocket-chip development to use chisel master, AKA the SNAPSHOT version of Chisel.

For the future rocket-chip releasing: I add the new `dev` branch and the future stable releasing of RC will based that. the backportable PR from `dev` to `master` will be merged. `master` will also be able to bump to new minor version of Chisel, since they are all backward compatible. After new major release of Chisel, `dev` will become the new `master` version, and `dev` will switch to next `master` version of Chisel   

**Related issue**: #3242, #3210, #3200, #3169, #2968

**Type of change**: feature request

**Impact**: no functional change

**Development Phase**: proposal

**Release Notes**

### CODE REVIEW

**Review by jerryz123 — CHANGES_REQUESTED** [review]
Can you just maintain a dev branch and keep the current master on stable chisel releases? Depending on chisel snapshots makes maintaining projects which depend on rocketchip untenable.

**Comment by sequencer** [comment]
OK, I'll create a `dev` branch, and get rid of `stable` branch.

**Review by jerryz123 — APPROVED** [review]

**Comment by sequencer** [comment]
Don't merge yet, I need to add CI.

**Comment by ZenithalHourlyRate** [comment]
Why would we need chisel plugin when running the rocket chip Generator class (`freechips.rocketchip.system.Generator`) in jvm. It has been compiled.

```
java.lang.AssertionError: assertion failed: The Chisel compiler plugin is now required for compiling Chisel code. Please see https://github.com/chipsalliance/chisel3#build-your-own-chisel-projects.
    scala.Predef$.assert(Predef.scala:279)
    chisel3.assert$.apply(VerificationStatement.scala:109)
    chisel3.Bundle.<init>(Aggregate.scala:1329)
    hardfloat.RawFloat.<init>(common.scala:68)
    hardfloat.rawFloatFromFN$.$anonfun$apply$23(rawFloatFromFN.scala:65)
    chisel3.WireFactory.apply(Data.scala:959)
    chisel3.WireFactory.apply$(Data.scala:957)
```

**Pull request merged**
