### PR TITLE
Disable the RemoveUnused scalafix rule

### PR DESCRIPTION
**Pull request by jerryz123**
Temporarily remove this so tests pass again. In bumping to 2.13, this becomes overly aggressive.

**Related issue**: 

**Type of change**: bug report | feature request | other enhancement

**Impact**: no functional change | API addition (no impact on existing code) | API modification

**Development Phase**: proposal |  implementation

**Release Notes**

### CODE REVIEW

**Comment by jerryz123** [comment]
Test 2/3 are failing due to unrelated, @sequencer can you approve?

**Comment by jerryz123** [comment]
I wonder if bumping OpenOCD will fix this. But if we bump OpenOCD, we might as well bump the rest of the stuff in rocket-tools. Pain.

**Comment by sequencer** [comment]
> I wonder if bumping OpenOCD will fix this. But if we bump OpenOCD, we might as well bump the rest of the stuff in rocket-tools. Pain.

yes, https://github.com/sequencer/rocket has bumped, it can work with Arch Linux, Debian, Nix for now.
But I'm enough with Ubuntu... So I didn't PR them.

**Comment by jerryz123** [comment]
I'll look at bumping rocket-tools

**Pull request merged**
