### PR TITLE
TileLink SRAM only check ECC errors on requested bytes

### PR DESCRIPTION
**Pull request by johningalls-sifive**
**Type of change**: bug report
**Impact**: bug fix

### CODE REVIEW

**Comment by terpstra** [comment]
So, I don't like this change for two reasons:
1. It inhibits correction
2. It uses MaskGen combinationally in the readout cycle

**Comment by terpstra** [comment]
I've prepared #2116 as my proposed fix. Can you rerun whatever test you used to validate your version?

**Comment by johningalls-sifive** [comment]
>     1. It inhibits correction
That's right: I propose that a request should not touch lanes that it doesn't ask for.

>     2. It uses MaskGen combinationally in the readout cycle
That's right: I assume that MaskGen is faster than SRAM read + ECC decode, and cheaper to re-compute rather than add Register bits for a/d_lanes.

> I've prepared #2116 as my proposed fix. Can you rerun whatever test you used to validate your version?
Yes, I confirm that #2116 also fixes the failing test.

**Comment by terpstra** [comment]
> > ```
> > 1. It inhibits correction
> > ```
> That's right: I propose that a request should not touch lanes that it doesn't ask for.

Just an FYI, if Chisel had per-lane read-enable, I would totally agree with you and have implemented it your way. But @jackkoenig doesn't care about power.

**Pull request closed without merging**
