### PR TITLE
Bump to Chisel 3.5.6

### PR DESCRIPTION
**Pull request by sequencer**
**Related issue**: blocked by #3196

**Type of change**:  other enhancement

**Impact**: no functional change

**Development Phase**: implementation

**Release Notes**

### CODE REVIEW

**Comment by jackkoenig** [comment]
3.5.6 probably hasn't yet been fully deployed to all mirrors and CDNs, but should be within a few hours.

**Comment by sequencer** [comment]
Ubuntu `apt install` in CI is so unstable......

**Comment by jerryz123** [comment]
Can this wait for #3156 ? I'm bumping too many things at the moment.

**Comment by sequencer** [comment]
#3196 ? OK!

**Comment by sequencer** [comment]
Merge it due to #3196 merged.

**Pull request merged**
