### PR TITLE
FIX (improve-boot-1): change reset vector address

### PR DESCRIPTION
**Pull request by T-K-233**
**Related issue**: 

**Type of change**: other enhancement

**Impact**: no functional change

**Development Phase**: implementation

**Release Notes**

### CODE REVIEW

**Comment by T-K-233** [comment]
Note: this depends on [testchipip #170](https://github.com/ucb-bar/testchipip/pull/170)

**Comment by ZenithalHourlyRate** [comment]
rocketchip itself does not depend on testchipip, that dependency is not valid.

If you want to change the bootrom reset vector, you should also change `bootrom/bootrom.S`, otherwise it will malfunction.

Or you can use `BootROMLocated` to override the reset vector in your target framework (maybe chipyard?)

One example I can give you is
https://github.com/OpenRigil/openrigil-rtl/blob/710dc7cec0302b79feda1c1c6e0bebe66d776188/sanitytests/rocketchip/src/OpenRigil.scala#L93-L126

**Comment by ZenithalHourlyRate** [comment]
> I wonder if there's a reason why we set the reset vector to 0x40 offset...? If not, I can also make a change to the bootrom and linker script here then.

As you can see in `bootrom/linker.ld`, 0x10000 is for `_start`, which jumps to DRAM directly, and 0x10040 is for `_hang`, which will wait for an interrupt from the debug module. By default, the rocket chip emulator starts by waiting for a debug request from htif.

> I prefer to not change the bootrom here.

Agreed.

**Comment by T-K-233** [comment]
> > I wonder if there's a reason why we set the reset vector to 0x40 offset...? If not, I can also make a change to the bootrom and linker script here then.
> 
> As you can see in `bootrom/linker.ld`, 0x10000 is for `_start`, which jumps to DRAM directly, and 0x10040 is for `_hang`, which will wait for an interrupt from the debug module. By default, the rocket chip emulator starts by waiting for a debug request from htif.


Is there a reason to arrange the `_start` and `_hang` sections as such in the BootROM? It's quite unintuitive that the program does not start from the base of the BootROM. 

One trouble I (and several others) have run into is when we tried to debug our design, we wanted to override the BootROM with some simple code (say, continuously dumping characters to UART), we were so confused why the program was not executing properly. The doc did not point out that the hart starts at this 0x10040 offset address....

If there's not specific reason, I wish to swap the `_start` and `_hang` sections, and make the reset PC at `0x10000` for everyone's convenience. 

Thanks.

**Comment by jerryz123** [comment]
You can configure the start and hang addresses when you specify a custom bootrom. The default here should not need to change

**Comment by jerryz123** [comment]
Closing, the default bootrom should not change

**Pull request closed without merging**
