### PR TITLE
Bump Chisel and FIRRTL along 3.4.x/1.4.x branches

### PR DESCRIPTION
**Pull request by seldridge**
Bump chisel3 to the HEAD of the 3.4.x branch and FIRRTL to the head of the 1.4.x branch.

**Related issue**: 

**Type of change**: other enhancement

**Impact**: no functional change

**Development Phase**: proposal

**Release Notes**

### CODE REVIEW

**Review by mwachs5 — APPROVED** [review]

**Comment by sequencer** [comment]
Maybe it’s time to get rid of building from source for rocketchip?

**Comment by seldridge** [comment]
> Maybe it’s time to get rid of building from source for rocketchip?

Totally for this. I think Jack was looking into it.

Unrelated, I have no idea what these semanticdb failures are in the regressions. I have not tried to investigate locally.

**Comment by jackkoenig** [comment]
> Totally for this. I think Jack was looking into it.

Yeah we should probably just not build from source, I'll switch it to the published versions.

**Comment by sequencer** [comment]
> Yeah we should probably just not build from source, I'll switch it to the published versions.

Did that for you, seems your are a little overloaded. ;p

**Comment by jackkoenig** [comment]
Superseded by move to published dependencies.

**Pull request closed without merging**
