### PR TITLE
TLToAXI4 should not block AXI4-b writeacks indefinitely

### PR DESCRIPTION
**Pull request by jerryz123**
https://github.com/chipsalliance/rocket-chip/blob/025184e1a0fdd8338eb0f66ad9ab33587b619854/src/main/scala/tilelink/ToAXI4.scala#L205-L209

The current arbitration policy in the TLToAXI4 converter always prioritizes AXI4 r-channel responses. This policy leads to starvation for clients waiting for a AccessAck, when the AXI4 r-channel is saturated. For example, a system where the L2 cache evicts a line, then saturates AXI4 with reads, may stall indefinitely waiting for a WriteAck.

This PR implements an alternate policy that stalls for b-channel acks if the b-channel ack has been blocked for 7 consecutive cycles. This is just one possible approach to avoid the indefinite stall. 

**Type of issue**: bug report 

**Development Phase**: implementation

### CODE REVIEW

**Comment by jerryz123** [comment]
@hcook @terpstra

**Comment by hcook** [comment]
Ideally this would be a configurable policy, but I agree this approach will prevent starvation and so is better than the status quo. What led you to choose the number 7?

**Review by hcook — APPROVED** [review]

**Review by terpstra — CHANGES_REQUESTED** [review]
I believe @andrew-gouldey-sifive has a more complete solution which made this configurable.

Should this PR be closed?

**Review by terpstra — APPROVED** [review]
I agree a configurable policy would be better, but this is better than nothing.

**Pull request merged**
