### PR TITLE
Support vector-units w/o L1D$ access

### PR DESCRIPTION
**Pull request by sequencer**
Without upstreaming these patches, T1 cannot elaborate... We need decouple in the future. Since there is no current valid useVector implementations, I think this is safe to merge.

**Related issue**: 

**Type of change**: bug report | feature request | other enhancement

**Impact**: no functional change | API addition (no impact on existing code) | API modification

**Development Phase**: proposal |  implementation

**Release Notes**

### CODE REVIEW

**Review by jerryz123 — CHANGES_REQUESTED** [review]
My implementation requires this.
We can add another flag `usingVectorDCache`

**Comment by sequencer** [comment]
> My implementation requires this.
We can add another flag usingVectorDCache

Added `vectorUseDCache`

**Review by jerryz123 — APPROVED** [review]
Thanks! I appreciate it

**Comment by sequencer** [comment]
We should purge these uArch parameters dependencies eventually. But not now;p

**Comment by jerryz123** [comment]
@mergifyio copy master

**Comment by jerryz123** [comment]
@mergifyio copy master

**Pull request merged**
