### PR TITLE
Make AMBA package importing explicit

### PR DESCRIPTION
**Pull request by lordspacehog**
**Type of change**: other enhancement

**Impact**: no functional change

**Development Phase**: implementation

**Release Notes**
Updates AMBA to use standalone diplomacy module directly.

Fixes a small issue with builds using chisel source for diplomacy module.

### CODE REVIEW

**Review by jerryz123 — APPROVED** [review]
I can't comment on the mill changes, but the import package name change looks good.

Side note: we should probably run some linter to discard unused imports at some point.

**Comment by lordspacehog** [comment]
Agreed. I'm trying to fold in moving from wildcard imports to qualified imports in these changes to at least make things a little more traceable. once i get these all in, i'd love to decide on a set of scalafmt and scalafix rules to apply to the repo as well.

**Review by sequencer — APPROVED** [review]
I changed PR name to "Make AMBA package importing explicit"

**Comment by sequencer** [comment]
> Side note: we should probably run some linter to discard unused imports at some point.

I propose adding scalafix

**Comment by lordspacehog** [comment]
I plan to try and push through the rest of these import updates this week, after that i'll do a separate PR adding scalafix to the build.

**Pull request merged**
