### PR TITLE
switch chisel3 dependency to ivy and bump to chisel 3.4.3

### PR DESCRIPTION
**Pull request by sequencer**
**Related issue**: suppress #2844

**Type of change**: other enhancement

**Impact**: no functional change
 
**Development Phase**: implementation

**Release Notes**
Use ivy chisel3.

### CODE REVIEW

**Comment by jackkoenig** [comment]
I definitely think we should switch to using the published dependencies, but I'm not sure if we should delete the ability to use the submodules. Projects like Chipyard sometimes use a different commit of Chisel and FIRRTL and this obviously precludes that. The whole purpose of the `sourceDependency` stuff in the `build.sbt` is that it enables us to use the published artifacts while allowing users of rocket-chip to override and use submodules if they want.

That being said, if Chipyard folks are down to ditch the submodules, then I'm in favor. @alonamid @a0u @jerryz123 @ abejgonzalez, any thoughts?

**Comment by sequencer** [comment]
BTW, If it is possible, I'm willing to experimentally help Chipyard guys to migrate to mill, which provides a better build-from-source infra then sbt.

**Comment by jackkoenig** [comment]
@sequencer Since we merged https://github.com/chipsalliance/rocket-chip/pull/2847, can you rebase? I'm still of two minds about just deleting the submodules, but let's go for it. We can add them back if it's a problem for Chipyard or others.

**Comment by sequencer** [comment]
@jackkoenig Done :)

**Review by jackkoenig — APPROVED** [review]

**Comment by jackkoenig** [comment]
I think there's a question if we should turn on `autoclonetype2` (which will break downstream users) or just wait for it to be on by default in Chisel 3.5

**Comment by itviewer** [comment]
Should we remove the `.sbtopts` file and clean up the content in https://github.com/chipsalliance/rocket-chip/blob/master/README.md#-building-rocket-chip-with-an-ide and https://github.com/chipsalliance/rocket-chip/blob/master/CONTRIBUTING.md#-bumping-chisel-and-firrtl

**Comment by jackkoenig** [comment]
> Should we remove the .sbtopts file and clean up the content in https://github.com/chipsalliance/rocket-chip/blob/master/README.md#-building-rocket-chip-with-an-ide and https://github.com/chipsalliance/rocket-chip/blob/master/CONTRIBUTING.md#-bumping-chisel-and-firrtl

Yes, and any sbt plugins that aren't used by rocket-chip

**Comment by sequencer** [comment]
I’ll PR later this week.

**Pull request merged**
