### PR TITLE
make LazyModule.nodes accessable by users.

### PR DESCRIPTION
**Pull request by sequencer**
**Type of change**: other enhancement

**Impact**: API modification

**Development Phase**: implementation

**Release Notes**
1. make `LazyModule.nodes` accessable to user for debugging and reuse Nodes.
2. refactor `childrenIterator` to `nodeIterator`, add `nodeIterator` to access all children's `BaseNode`.

### CODE REVIEW

**Comment by terpstra** [comment]
Why do we need this? It makes the API more porous.

**Comment by sequencer** [comment]
Hello, @terpstra.
We(SiFive China) are experimentally using https://github.com/ucb-bar/chisel-testers2 to establish a TileLink unittest framework.
Thus beside extracting sub-`LazyModule` from Top `LazyModule` with `getChildren` API, we also need exporting nodes form these `LazyModule`s to reconstruct interfaces in the `tester2` side.

**Comment by sequencer** [comment]
Thank you!

**Comment by sequencer** [comment]
any chance to get this merged?

**Comment by terpstra** [comment]
Ah. Sorry about that. I thought you could merge it yourself after I approved it.

**Comment by sequencer** [comment]
Thank you! I don't have access to rc, so I can't merge it.

**Pull request merged**
