### PR TITLE
Debug: reduce default program buffer size since impebreak is an option

### PR DESCRIPTION
**Pull request by mwachs5**
Turn down the program buffer words to 2 and use implicit ebreak.

@timsifive is 2 program buffer words enough ?

### CODE REVIEW

**Comment by timsifive** [comment]
>
> @timsifive <https://github.com/timsifive> is 2 program buffer words
> enough ?
>
2 is enough. In fact OpenOCD won't even try to use more than that (assuming
impebreak, otherwise it will use 3).

**Comment by mwachs5** [comment]
Blergh. I forgot that `riscv-fesvr` is not as sophisticated, and *doesn't* utlize the `impebreak`. So none of the tests that use `riscv-fesvr` to load the program succeed.

I'll try turning it down to 4.

**Comment by mwachs5** [comment]
This is blocked on FESVR being updated to use less progbuf words as OpenOCD was.

**Comment by mwachs5** [comment]
This depends on https://github.com/riscv/riscv-fesvr/issues/48

**Comment by mwachs5** [comment]
this has been done long ago

**Pull request closed without merging**
