### PR TITLE
dret should be illegal outside debug mode

### PR DESCRIPTION
**Pull request by ernie-sifive**
**Related issue**: Issue #2022 

**Type of change**: bug report 

**Impact**: no functional change 

**Development Phase**: implementation

**Release Notes**

The dret instruction should throw an illegal instruction exception when executed outside debug mode.

### CODE REVIEW

**Comment by ernie-sifive** [comment]
@aswaterman @hcook Travis test 8 seems to be timing out with this change.  Any suggestions?

**Comment by aswaterman** [comment]
I don’t know what the travis tests do. Did you try restarting the travis build to see if it was a spurious failure? cc @richardxia - who’s the right person to ask?

**Comment by richardxia** [comment]
I don't know much about the Travis CI tests for rocket-chip, and I'm pretty sure it was the UCB crowd that set them up. @hcook, do you know about them? In the meantime, I just hit the restart button on that job, so we can see if it was spurious.

**Comment by aswaterman** [comment]
I’ll help debug tomorrow if it fails after a retry.

**Comment by ernie-sifive** [comment]
@aswaterman I looked a bit at the tests and some of them run code on both the simulated hardware and on spike and compare the results.  I took a look at spike and am wondering if it has the same issue with dret.  `riscv-isa-sim/riscv/insns/dret.h` seems to only require PRV_M.  It is not obvious how to check for debug mode.  Maybe add something like this?
```
if (state.pc >= 0x1000) throw trap_illegal_instruction(0);
```
dret.h:
```
require_privilege(PRV_M);
set_pc_and_serialize(STATE.dpc);
p->set_privilege(STATE.dcsr.prv);

/* We're not in Debug Mode anymore. */
STATE.dcsr.cause = 0;

if (STATE.dcsr.step)
  STATE.single_step = STATE.STEP_STEPPING;
```

**Comment by aswaterman** [comment]
Well, I retried the failing test, and it passed.  I'm going to write it off as a spurious infrastructural issue.  I'll deal with the Spike issue separately.

**Comment by hcook** [comment]
@aswaterman All PRs are now failing on this test

**Comment by aswaterman** [comment]
@hcook any idea why I was allowed to merge it?

**Comment by ernie-sifive** [comment]
Should revert until understood. Could be a random test so it sometimes passes and sometimes fails.

**Comment by aswaterman** [comment]
@ernie-sifive I'm working on replicating it locally.  If I fail to do so or can't find a quick solution, I'll revert, but I'll try to avoid doing so.

**Comment by aswaterman** [comment]
It was a four-character bug I probably should've caught in code review.  D'oh.  Fixed in #2036.

**Pull request merged**
